version: '3.8'  # Specify the Docker Compose version

services:
  frontend:
    build: mern/frontend
    ports:
      - "5173:5173"
    networks:
      - mern
  
  backend:
    build: mern/backend
    ports:
      - "5050:5050"
    networks:
      - mern
    environment:
      - MONGODB_URI=mongodb+srv://sudhinmern:OZzZOjSg0KFJ2qW2@mern.aaf6b.mongodb.net/?retryWrites=true&w=majority&appName=Mern

networks:
  mern:
    driver: bridge


